### ISSUE TITLE
Lots of errors...

### ISSUE THREAD

**Issue by Cheapskate01** [andystanton/glfw-skeleton#30]
Executing default...
    Executing configure...
    mkdir -p build
    cmake  ..
    -- The C compiler identification is GNU 4.8.4
    -- The CXX compiler identification is GNU 4.8.4
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    CMake Error at CMakeLists.txt:85 (ADD_SUBDIRECTORY):
      The source directory

        /home/cheapskate01/glfw-skeleton-master/lib/glfw

      does not contain a CMakeLists.txt file.

    CMake Error at CMakeLists.txt:93 (ADD_SUBDIRECTORY):
      The source directory

        /home/cheapskate01/glfw-skeleton-master/lib/glew

      does not contain a CMakeLists.txt file.

    CMake Error at CMakeLists.txt:105 (ADD_SUBDIRECTORY):
      The source directory

        /home/cheapskate01/glfw-skeleton-master/lib/gmock

      does not contain a CMakeLists.txt file.

    CMake Error at CMakeLists.txt:110 (SET_PROPERTY):
      set_property could not find TARGET gmock.  Perhaps it has not yet been
      created.

    CMake Error at CMakeLists.txt:111 (SET_PROPERTY):
      set_property could not find TARGET gmock_main.  Perhaps it has not yet been
      created.
    
    
    CMake Error at CMakeLists.txt:112 (SET_PROPERTY):
      set_property could not find TARGET gtest.  Perhaps it has not yet been
      created.
    
    
    CMake Error at CMakeLists.txt:113 (SET_PROPERTY):
      set_property could not find TARGET gtest_main.  Perhaps it has not yet been
      created.
    
    
    CMake Error at CMakeLists.txt:123 (ADD_SUBDIRECTORY):
          The source directory
    
        /home/cheapskate01/glfw-skeleton-master/lib/bandit
    
      does not contain a CMakeLists.txt file.
    
    
    -- Copying contents of directory /home/cheapskate01/glfw-skeleton-master/src/shaders to          /home/cheapskate01/glfw-skeleton-master/build/bin
    -- Copying file skull.vertexshader
    -- Copying file skull.fragmentshader
    -- Configuring incomplete, errors occurred!
    See also "/home/cheapskate01/glfw-skeleton-master/build/CMakeFiles/CMakeOutput.log".
    rake aborted!
    Command failed with status (1): [cmake  .....]
    /home/cheapskate01/glfw-skeleton-master/rakefile:67:in `block (2 levels) in <top (required)>'
    /home/cheapskate01/glfw-skeleton-master/rakefile:66:in `chdir'
    /home/cheapskate01/glfw-skeleton-master/rakefile:66:in `block in <top (required)>'
    /home/cheapskate01/glfw-skeleton-master/rakefile:103:in `block in <top (required)>'
    Tasks: TOP => configure
    (See full trace by running task with --trace)

**Comment by Cheapskate01** [comment]
That's what I get from rake default start

**Comment by andystanton** [comment]
Hi @Cheapskate01 

The libraries that glfw-skeleton depends on are git submodules so you need to clone with the `--recursive` tag. As you've already cloned you should be able to run this command from the project root:

```TerminalSession
$ git submodule update --init --recursive
```

That should then check out the bits you're missing and `rake default start` should start working.

If you're cloning from scratch you want this command:

```TerminalSession
$ git clone https://github.com/andystanton/glfw-skeleton.git --recursive
```
